[features]
seeds = false
[programs.localnet]
wobble_synth = "8ptgXekj3hdRqdXvrW8cr55ZoMNLeyqa7Xp13XAAUMBQ"
[programs.devnet]
wobble_synth = "8ptgXekj3hdRqdXvrW8cr55ZoMNLeyqa7Xp13XAAUMBQ"
[programs.mainnet]
wobble_synth = "54mzQZxsFhqshuPkQhgHU8EBKTnLMtdv51Lpx8Cj4YMB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/shashank/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
